name: Manual Java Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to build for'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: echo "${{ GITHUB.EVENT_NAME }}"

      - name: Print environment
        run: echo "${{ GITHUB.WORKFLOW }}"
        
      - name: Print environment
        run: echo "You selected the ${{ github.event.inputs.environment }} environment."
